# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'P5.js Viewer 0.08' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    # Pods for P5.js Viewer 0.08
  pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git', :branch => 'stable'


end
