# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'P5.js Viewer 0.01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for P5.js Viewer 0.01
  pod "GCDWebServer", "~> 3.0"

  target 'P5.js Viewer 0.01Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'P5.js Viewer 0.01UITests' do
    # Pods for testing
  end

end
